---
name: Codespell

on:
  pull_request:
  push:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@v1
        with:
          ignore_words_list: gost,erro,blok
